<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>FanboxUpdater</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <Version>1.0.2</Version>
    <StartupObject>Updater.App.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="app.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WPF-UI" Version="3.0.5" />
    <PackageReference Include="Velopack" Version="0.0.*" />
    <ProjectReference Include="..\Updater.Core\Updater.Core.csproj" />
    <ProjectReference Include="..\Updater.Providers.Fanbox\Updater.Providers.Fanbox.csproj" />
  </ItemGroup>

</Project>
